# Generated by Django 4.1.1 on 2022-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0002_province_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
