# Generated by Django 4.1.1 on 2022-10-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0003_alter_district_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
