# Generated by Django 4.1.1 on 2022-10-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0005_district_code_en_district_code_kh_province_code_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_en', models.CharField(default='', max_length=255)),
                ('code_kh', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(max_length=500)),
                ('name_kh', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdrapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_en', models.CharField(default='', max_length=255)),
                ('code_kh', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(max_length=500)),
                ('name_kh', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('commune_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdrapp.commune')),
            ],
        ),
    ]
