# Generated by Django 4.1.1 on 2022-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0006_commune_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(default='', max_length=500)),
                ('name_kh', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
