# Generated by Django 4.1.1 on 2022-10-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0009_watersupplyoption_watersupplyoptionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('water_supply_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdrapp.watersupplyoption')),
                ('water_supply_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdrapp.watersupplytype')),
            ],
        ),
    ]
