# Generated by Django 4.1.1 on 2022-10-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0011_alter_watersupplytypeoption_water_supply_option_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincedistrict', to='mdrapp.province'),
        ),
    ]
