# Generated by Django 4.1.1 on 2022-10-13 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0013_alter_commune_district_id_alter_village_commune_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_created_by', to=settings.AUTH_USER_MODEL)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_district', to='mdrapp.district')),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_province', to='mdrapp.province')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_updated_by', to=settings.AUTH_USER_MODEL)),
                ('water_supply_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_type', to='mdrapp.watersupplytype')),
            ],
        ),
    ]
