# Generated by Django 4.1.1 on 2022-10-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0014_watersupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
