# Generated by Django 4.1.1 on 2022-11-25 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0015_watersupply_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupply',
            name='commune_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_commune', to='mdrapp.commune'),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='is_risk_enviroment_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='total_family',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='utm_x',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='utm_y',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='village_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_village', to='mdrapp.village'),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='water_supply_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
