# Generated by Django 4.1.1 on 2022-11-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0016_watersupply_commune_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupply',
            name='construction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
