# Generated by Django 3.2.16 on 2022-11-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0017_watersupply_construction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupply',
            name='beneficiary_total_family',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='beneficiary_total_family_indigenous',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='beneficiary_total_family_poor_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='beneficiary_total_family_poor_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='beneficiary_total_family_vulnerable',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='beneficiary_total_people',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='beneficiary_total_women',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='constructed_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='managed_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='management_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='source_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
