# Generated by Django 3.2.16 on 2022-11-28 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0018_auto_20221128_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupplyoptionvalue',
            name='water_supply_option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyoption_value', to='mdrapp.watersupplyoption'),
        ),
    ]
