# Generated by Django 3.2.16 on 2022-11-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0019_alter_watersupplyoptionvalue_water_supply_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_supply_option_value', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('water_supply_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyoptionvalue_option', to='mdrapp.watersupplyoption')),
                ('watersupply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyoptionvalue_watersupply', to='mdrapp.watersupply')),
            ],
        ),
    ]
