# Generated by Django 3.2.16 on 2022-11-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0021_watersupplyoption_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('well_height', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('well_filter_height', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('well_water_supply', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('well_nirostatic', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('well_watar_quality', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('well_water_quality_check', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('well_status', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('well_status_reason', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('watersupply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplywell_watersupply', to='mdrapp.watersupply')),
            ],
        ),
    ]
