# Generated by Django 3.2.16 on 2022-11-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0022_watersupplywell'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplywell',
            name='well_nirodynamic',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
