# Generated by Django 3.2.16 on 2022-12-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0024_watersupplyrainwaterharvesting_watersupplypipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplykiosk',
            name='water_quality_checking',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
