# Generated by Django 4.1.4 on 2023-01-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0025_watersupplykiosk_water_quality_checking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('status_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='watersupply',
            name='main_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupply_status', to='mdrapp.status'),
        ),
    ]
