# Generated by Django 4.1.4 on 2023-01-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0026_status_watersupply_main_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_name_kh',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
