# Generated by Django 4.1.4 on 2023-01-04 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0027_status_status_name_kh'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyWorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='', null=True)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyworkflow_status', to='mdrapp.status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyworkflow_user_id', to=settings.AUTH_USER_MODEL)),
                ('watersupply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyworkflow_watersupply', to='mdrapp.watersupply')),
            ],
        ),
    ]
