# Generated by Django 4.1.4 on 2023-01-08 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0028_watersupplyworkflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyWellOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplywelloptionvalue_option', to='mdrapp.watersupplyoption')),
                ('value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplywelloptionvalue_value', to='mdrapp.watersupplyoptionvalue')),
                ('water_supply_well_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplywelloptionvalue_watersupplywell', to='mdrapp.watersupplywell')),
            ],
        ),
    ]
