# Generated by Django 4.1.4 on 2023-01-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0029_watersupplywelloptionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_data_verifier_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_data_verifier_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_provincial_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entry_province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdataentry_province', to='mdrapp.province')),
                ('provincial_department_head_province_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincialdepartmenthead_province', to='mdrapp.province')),
            ],
        ),
    ]
