# Generated by Django 4.1.4 on 2023-01-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0030_user_is_data_verifier_1_user_is_data_verifier_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_entry_province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdataentry_province', to='mdrapp.province'),
        ),
        migrations.AddField(
            model_name='user',
            name='provincial_department_head_province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincialdepartmenthead_province', to='mdrapp.province'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='data_entry_province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetaildataentry_province', to='mdrapp.province'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='provincial_department_head_province_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userdetailprovincialdepartmenthead_province', to='mdrapp.province'),
        ),
    ]
