# Generated by Django 4.1.4 on 2023-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0032_watersupplyqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
