# Generated by Django 4.1.4 on 2023-01-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0033_status_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name_en', models.TextField(blank=True, default='', null=True)),
                ('name_kh', models.TextField(blank=True, default='', null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False)),
                ('is_edit', models.BooleanField(default=False)),
                ('is_detail', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_data_entry', models.BooleanField(default=False)),
                ('is_provincial_department_head', models.BooleanField(default=False)),
                ('is_data_verifier_1', models.BooleanField(default=False)),
                ('is_data_verifier_2', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False)),
                ('is_head_department', models.BooleanField(default=False)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menupermission', to='mdrapp.menu')),
            ],
        ),
    ]
