# Generated by Django 4.1.4 on 2023-01-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0034_menu_menupermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupply',
            name='utm_x',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='watersupply',
            name='utm_y',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
    ]
