# Generated by Django 4.1.4 on 2023-01-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0035_alter_watersupply_utm_x_alter_watersupply_utm_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplyoption',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
