# Generated by Django 4.1.4 on 2023-01-27 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0036_watersupplyoption_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('water_supply_code', models.TextField(blank=True, default='', null=True)),
                ('total_family', models.IntegerField(blank=True, default=0, null=True)),
                ('utm_x', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True)),
                ('utm_y', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True)),
                ('is_risk_enviroment_area', models.BooleanField(default=True)),
                ('construction_date', models.DateField(blank=True, null=True)),
                ('source_budget', models.IntegerField(blank=True, default=0, null=True)),
                ('constructed_by', models.TextField(blank=True, default='', null=True)),
                ('management_type', models.IntegerField(blank=True, default=0, null=True)),
                ('managed_by', models.TextField(blank=True, default='', null=True)),
                ('beneficiary_total_people', models.IntegerField(blank=True, default=0, null=True)),
                ('beneficiary_total_women', models.IntegerField(blank=True, default=0, null=True)),
                ('beneficiary_total_family', models.IntegerField(blank=True, default=0, null=True)),
                ('beneficiary_total_family_poor_1', models.IntegerField(blank=True, default=0, null=True)),
                ('beneficiary_total_family_poor_2', models.IntegerField(blank=True, default=0, null=True)),
                ('beneficiary_total_family_vulnerable', models.IntegerField(blank=True, default=0, null=True)),
                ('beneficiary_total_family_indigenous', models.IntegerField(blank=True, default=0, null=True)),
                ('commune_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyhistory_commune', to='mdrapp.commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyhistory_created_by', to=settings.AUTH_USER_MODEL)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyhistory_district', to='mdrapp.district')),
                ('main_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyhistory_status', to='mdrapp.status')),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyhistory_province', to='mdrapp.province')),
                ('village_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyhistory_village', to='mdrapp.village')),
                ('water_supply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyhistory_watersupply', to='mdrapp.watersupply')),
            ],
        ),
    ]
