# Generated by Django 4.1.4 on 2023-02-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0037_watersupplyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplypipe',
            name='area_covering',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='watersupplypipe',
            name='pipe_length',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='WaterSupplyPipeOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplypipeoptionvalue_option', to='mdrapp.watersupplyoption')),
                ('value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplypipeoptionvalue_value', to='mdrapp.watersupplyoptionvalue')),
                ('water_supply_pipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplypipeoptionvalue_watersupplypipe', to='mdrapp.watersupplypipe')),
            ],
        ),
    ]
