# Generated by Django 4.1.4 on 2023-02-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0038_watersupplypipe_area_covering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyKioskOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplykioskoptionvalue_option', to='mdrapp.watersupplyoption')),
                ('value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplykioskoptionvalue_value', to='mdrapp.watersupplyoptionvalue')),
                ('water_supply_kiosk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplykioskoptionvalue_watersupplypipe', to='mdrapp.watersupplykiosk')),
            ],
        ),
    ]
