# Generated by Django 4.1.4 on 2023-02-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0039_watersupplykioskoptionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualityCheckedParamater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('parameter', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('unit', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('standard_of_drinking_water', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSupplyQuanlityCheckParamater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('water_quanlity_check_parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyquanlitycheckparamater_water_quanlity_check_parameter', to='mdrapp.waterqualitycheckedparamater')),
                ('water_supply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyquanlitycheckparamater_watersupply', to='mdrapp.watersupply')),
            ],
        ),
    ]
