# Generated by Django 4.1.4 on 2023-02-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0040_waterqualitycheckedparamater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitycheckedparamater',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitycheckedparamater',
            name='parameter_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitycheckedparamater',
            name='standard_of_drinking_water',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='waterqualitycheckedparamater',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
