# Generated by Django 4.1.4 on 2023-02-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0041_alter_waterqualitycheckedparamater_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterqualitycheckedparamater',
            name='field_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
