# Generated by Django 4.1.4 on 2023-02-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0042_waterqualitycheckedparamater_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupply',
            name='is_water_quality_check',
            field=models.BooleanField(default=False),
        ),
    ]
