# Generated by Django 4.1.4 on 2023-02-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0043_watersupply_is_water_quality_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupply',
            name='decimal_degress_lat',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='decimal_degress_lng',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='map_unit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='mds_x_degress',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='mds_x_minute',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='mds_x_second',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='mds_y_degress',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='mds_y_minute',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watersupply',
            name='mds_y_second',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=20, null=True),
        ),
    ]
