# Generated by Django 4.1.4 on 2023-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0044_watersupply_decimal_degress_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupply',
            name='utm_x',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='watersupply',
            name='utm_y',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=30, null=True),
        ),
    ]
