# Generated by Django 4.1.4 on 2023-02-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0045_alter_watersupply_utm_x_alter_watersupply_utm_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplyrainwaterharvesting',
            name='water_quality_checking',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
