# Generated by Django 4.1.4 on 2023-02-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0046_watersupplyrainwaterharvesting_water_quality_checking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watersupplykioskoptionvalue',
            name='water_supply_kiosk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplykioskoptionvalue_watersupplykiosk', to='mdrapp.watersupplykiosk'),
        ),
    ]
