# Generated by Django 4.1.4 on 2023-02-20 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0047_alter_watersupplykioskoptionvalue_water_supply_kiosk_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyPipePrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('source_type_of_water', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('abilty_of_produce_water', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('underground_pool_storage', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pool_air', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pool_filter', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('number_of_link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('water_quality_check', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('status_no_reason', models.TextField(blank=True, default='', null=True)),
                ('pipe_length', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('area_covering', models.TextField(blank=True, default='', null=True)),
                ('is_has_license', models.BooleanField(default=False)),
                ('license_registered_date', models.DateField(blank=True, null=True)),
                ('license_expired_date', models.DateField(blank=True, null=True)),
                ('watersupply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplypipeprivate_watersupply', to='mdrapp.watersupply')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSupplyPipePrivateOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplypipeprivateoptionvalue_option', to='mdrapp.watersupplyoption')),
                ('value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplypipeprivateoptionvalue_value', to='mdrapp.watersupplyoptionvalue')),
                ('water_supply_pipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplypipeprivateoptionvalue_watersupplypipewater', to='mdrapp.watersupplypipeprivate')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSupplyAirWaterOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyairwateroptionvalue_option', to='mdrapp.watersupplyoption')),
                ('value_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyairwateroptionvalue_value', to='mdrapp.watersupplyoptionvalue')),
                ('water_supply_airwater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyairwateroptionvalue_watersupplykioskwater', to='mdrapp.watersupplykiosk')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSupplyAirWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('source_type_of_water', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('abilty_of_produce_water', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filter_system', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('water_quality_checking', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('status_no_reason', models.TextField(blank=True, default='', null=True)),
                ('watersupply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watersupplyairwater_watersupply', to='mdrapp.watersupply')),
            ],
        ),
    ]
