# Generated by Django 4.1.4 on 2023-03-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0051_watersupply_crated_at_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_en', models.CharField(default='', max_length=255)),
                ('code_kh', models.CharField(default='', max_length=255)),
                ('name_en', models.CharField(max_length=500)),
                ('name_kh', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_population', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='total_population',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='total_population',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='total_population',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='total_population',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=25, null=True),
        ),
    ]
