# Generated by Django 4.1.4 on 2023-04-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0052_country_commune_total_population_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='coordinate_border',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='coordinate_center',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='coordinate_border',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='coordinate_center',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='coordinate_border',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='coordinate_center',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='coordinate_border',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='coordinate_center',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='coordinate_border',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='coordinate_center',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
