# Generated by Django 4.1.1 on 2023-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdrapp', '0053_commune_coordinate_border_commune_coordinate_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='form_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
